# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='groups',
        ),
    ]
